package org.carapaceproxy.server.mapper.requestmatcher;

/* Generated By:JavaCC: Do not edit this line. RequestMatcherConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RequestMatcherConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALL = 5;
  /** RegularExpression Id. */
  int REGEXP_DEF = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int HTTPS = 10;
  /** RegularExpression Id. */
  int O_BRACKET = 11;
  /** RegularExpression Id. */
  int C_BRACKET = 12;
  /** RegularExpression Id. */
  int REGEXP = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"all\"",
    "\"regexp\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"https\"",
    "\"(\"",
    "\")\"",
    "<REGEXP>",
  };

}
